development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ceocgizhzklhnz:e7cc7ce5181ddc331800bf9321c4a6a118f1f1285f42733818d9f18aeea6863e@ec2-23-23-186-157.compute-1.amazonaws.com:5432/d4uijeocd9vv80
